// Generated by CoffeeScript 1.10.0
define(['jquery'], function($) {
  'use strict';
  var _loadArticle, _privateMethod, openArticle, publicReturn, someMethod;
  _privateMethod = function(x) {
    return console.log(x);
  };
  _loadArticle = function() {};
  someMethod = function(x) {
    return _privateMethod(x);
  };
  openArticle = function() {
    return console.log('open');
  };
  publicReturn = {
    someMethod: someMethod,
    openArticle: openArticle
  };
  return publicReturn;
});
